apiVersion: v1
kind: LimitRange
metadata:
  name: app-limit-range
  namespace: probe-demo
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: "200m"
      memory: 256Mi
    type: Container
