apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-liveness-probe
  namespace: probe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-liveness-probe
  template:
    metadata:
      labels:
        app: tcp-liveness-probe
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-liveness-probe-service
  namespace: probe-demo
spec:
  selector:
    app: tcp-liveness-probe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
