apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-account-admin
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-account-admin-binding
subjects:
- kind: User
  name: <USERNAME>  # Replace <USERNAME> with the actual user or service account name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: service-account-admin
  apiGroup: rbac.authorization.k8s.io


