apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-quota
  namespace: probe-demo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
