apiVersion: apps/v1
kind: Deployment
metadata:
  name: specific-deployment
  namespace: probe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: specific-app
  template:
    metadata:
      labels:
        app: specific-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
