name: Trivy Scan and Report

on:
  push:
    branches:
      - main
    paths:
      - 'deployments/**'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          echo "$KUBECONFIG" > $HOME/.kube/config

      - name: Run Trivy Scans
        run: |
          kubectl apply -f https://raw.githubusercontent.com/aquasecurity/trivy-operator/main/deploy/crd/v1alpha1/vulnerabilityreports.crd.yaml
          kubectl apply -f https://raw.githubusercontent.com/aquasecurity/trivy-operator/main/deploy/crd/v1alpha1/configauditreports.crd.yaml
          kubectl apply -f https://raw.githubusercontent.com/aquasecurity/trivy-operator/main/deploy/crd/v1alpha1/rbacassessmentreports.crd.yaml
          kubectl apply -f https://raw.githubusercontent.com/aquasecurity/trivy-operator/main/deploy/crd/v1alpha1/ciskubebenchreports.crd.yaml

      - name: Fetch Scan Reports
        run: |
          kubectl get vulnerabilityreports -o json > vulnerabilityreports.json
          kubectl get configauditreports -o json > configauditreports.json
          kubectl get rbacassessmentreports -o json > rbacassessmentreports.json
          kubectl get ciskubebenchreports -o json > ciskubebenchreports.json

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: trivy-scan-reports
          path: |
            vulnerabilityreports.json
            configauditreports.json
            rbacassessmentreports.json
            ciskubebenchreports.json
